name: Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: docs-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  docs_hub:
    if: false
    name: docs (qadence-hub)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install JetBrains Mono font
        run: |
          sudo apt install -y wget unzip fontconfig
          wget https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip
          unzip JetBrainsMono-2.304.zip -d JetBrainsMono
          mkdir -p /usr/share/fonts/truetype/jetbrains
          cp JetBrainsMono/fonts/ttf/*.ttf /usr/share/fonts/truetype/jetbrains/
          fc-cache -f -v

      - name: Install graphviz
        run: sudo apt-get install -y graphviz

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Hatch
        run: |
          pip install hatch

      - name: Build docs
        run: |
          hatch -v run docs:build


  docs_measurements:
    if: false
    name: docs (qadence-measurements)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: qadence-measurements
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install JetBrains Mono font
        run: |
          sudo apt install -y wget unzip fontconfig
          wget https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip
          unzip JetBrainsMono-2.304.zip -d JetBrainsMono
          mkdir -p /usr/share/fonts/truetype/jetbrains
          cp JetBrainsMono/fonts/ttf/*.ttf /usr/share/fonts/truetype/jetbrains/
          fc-cache -f -v

      - name: Install graphviz
        run: sudo apt-get install -y graphviz

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Hatch
        run: |
          pip install hatch

      - name: Build docs
        run: |
          hatch -v run docs:build

  docs_mitigations:
    if: false
    name: docs (qadence-mitigations)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: qadence-mitigations
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install JetBrains Mono font
        run: |
          sudo apt install -y wget unzip fontconfig
          wget https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip
          unzip JetBrainsMono-2.304.zip -d JetBrainsMono
          mkdir -p /usr/share/fonts/truetype/jetbrains
          cp JetBrainsMono/fonts/ttf/*.ttf /usr/share/fonts/truetype/jetbrains/
          fc-cache -f -v

      - name: Install graphviz
        run: sudo apt-get install -y graphviz

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Hatch
        run: |
          pip install hatch

      - name: Build docs
        run: |
          hatch -v run docs:build

  docs_libs:
    if: false
    name: docs (qadence-libs)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: qadence-libs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install JetBrains Mono font
        run: |
          sudo apt install -y wget unzip fontconfig
          wget https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip
          unzip JetBrainsMono-2.304.zip -d JetBrainsMono
          mkdir -p /usr/share/fonts/truetype/jetbrains
          cp JetBrainsMono/fonts/ttf/*.ttf /usr/share/fonts/truetype/jetbrains/
          fc-cache -f -v

      - name: Install graphviz
        run: sudo apt-get install -y graphviz

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Hatch
        run: |
          pip install hatch

      - name: Build docs
        run: |
          hatch -v run docs:build
