name: Upload coverage to Codecov

on:
  pull_request: 

jobs:
  upload-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload coverage.xml to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: test-qadence-libs/coverage.xml
        #   token: ${{ secrets.CODECOV_TOKEN }}